# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0009_auto_20160324_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Text'),
        ),
    ]
